### ISSUE TITLE
增加ChhoeTaigi ê詞庫

### ISSUE THREAD

**Issue by ngoohebi** [shiami/PhahTaigi_Android#13]
有時間再考慮納入何種詞庫

**Comment by sih4sing5hong5** [comment]
借問一下，這馬有用著啥物辭典？

**Comment by ngoohebi** [comment]
@sih4sing5hong5 Kan-na īng Kàu-io̍k-pōo ê.

**Comment by ngoohebi** [comment]
Guá tshiú thâu koh ū 台日大辭典, iah bô sî-kan tshú-lí.

**Comment by ngoohebi** [comment]
Kàu-io̍k-pōo ê koh ū tē-hong khiunn-kháu ê jī-sû ài ka-ji̍p.

**Comment by sih4sing5hong5** [comment]
https://github.com/sih4sing5hong5/tai5-uan5_gian5-gi2_hok8-bu7/wiki/Taiwanese-Corpus語料
這是我收集的
你若有需要，我嘛會當輸出itaigi ê sû

**Comment by ngoohebi** [comment]
@sih4sing5hong5 Tsiânn kám-kik, guá ē tāu-tāu-á lâi tsham-khó kap tshú-lí.

Guá tsit-má siu sû ū khah pó-siú, guá ka-tī sî-kan mā iú-hān, hàn-jī ê pōo-hūn kan-na beh īng Kàu-io̍k-pōo sû-tián ê tsu-liāu.
Lô-má-jī ê pōo-hūn, ē uì khah tsē lâng sú-iōng ê sû-tián khai-sí tsò.

Lóo-la̍t!

**Comment by sih4sing5hong5** [comment]
guá huat-kak su-ji̍p-huat ū `Suí-ke水雞`
kàu-io̍k-pōo 干焦 bô tsit-ê im

**Comment by ngoohebi** [comment]
@sih4sing5hong5 
Ū--neh!

tsuí-ke/tsuí-kue　又唸作suí-ke/suí-kue

**Comment by sih4sing5hong5** [comment]
@shiami 歹勢

**Comment by ngoohebi** [comment]
@sih4sing5hong5 Bô iàu-kín--lah! Ū būn-tê koh tshiánn lí thê-tshut, lóo-la̍t!

**Comment by ngoohebi** [comment]
Chiah koh整理ChhoeTaigi詞庫資料ka入。

https://github.com/ChhoeTaigi/ChhoeTaigiDatabase
